import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button';
import BottomNavigationAction from '@mui/material/BottomNavigationAction';
import BottomNavigation from '@mui/material/BottomNavigation';
import { LocationOn, Favorite } from '@mui/icons-material';
import { useState } from 'react';

const Home: NextPage = () => {
 let  [value,setValue] =useState(0);


  return (
    <div className={styles.container}>
      <Head>
        <title>Trias Hackathon </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
   
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Trias Hackathon</a>
        </h1>

     
      </main>

      <footer className={styles.footer}>
      <BottomNavigation
  showLabels
  value={value}
  onChange={(event, newValue) => {
    setValue(newValue);
  }}
>
  <BottomNavigationAction label="Recents" icon={<LocationOn />} />
  <BottomNavigationAction label="Favorites" icon={<LocationOn />} />
  <BottomNavigationAction label="Nearby" icon={<LocationOn />} />
</BottomNavigation>
        {/* <a
        
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Trias
          </span>
        </a> */}
      </footer>
    </div>
  )
}

export default Home


